// Generated only from manufacturer CSV; independent of RTL.
struct Golden { unsigned pins, next; };
static Golden golden(unsigned inst,unsigned controls,unsigned u,unsigned m) {
const unsigned input=controls&15, y=(controls>>4)&15, serial=(controls>>8)&15;
const unsigned UZ=u&1,UC=(u>>1)&1,UN=(u>>2)&1,UV=(u>>3)&1;
const unsigned MZ=m&1,MC=(m>>1)&1,MN=(m>>2)&1,MV=(m>>3)&1;
const unsigned IZ=input&1,IC=(input>>1)&1,IN=(input>>2)&1,IV=(input>>3)&1;
const unsigned YZ=y&1,YC=(y>>1)&1,YN=(y>>2)&1,YV=(y>>3)&1;
const unsigned S0=serial&1,SN=(serial>>1)&1,Q0=(serial>>2)&1,QN=(serial>>3)&1;
unsigned un=0,mn=0,out_y=0,ct=0,carry=0,sh=0,en=0;
switch(inst&63) {
case 0: un=((MZ)<<0) | ((MC)<<1) | ((MN)<<2) | ((MV)<<3); mn=((YZ)<<0) | ((YC)<<1) | ((YN)<<2) | ((YV)<<3); out_y=u; ct=((UN ^ UV) | UZ); carry=UC; break;
case 1: un=((1)<<0) | ((1)<<1) | ((1)<<2) | ((1)<<3); mn=((1)<<0) | ((1)<<1) | ((1)<<2) | ((1)<<3); out_y=u; ct=(((UN ^ UV) ^ 1) & (UZ ^ 1)); carry=UC; break;
case 2: un=((MZ)<<0) | ((MC)<<1) | ((MN)<<2) | ((MV)<<3); mn=((UZ)<<0) | ((UC)<<1) | ((UN)<<2) | ((UV)<<3); out_y=u; ct=(UN ^ UV); carry=UC; break;
case 3: un=((0)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3); mn=((0)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3); out_y=u; ct=((UN ^ UV) ^ 1); carry=UC; break;
case 4: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((MV)<<1) | ((IN)<<2) | ((MC)<<3); out_y=u; ct=UZ; carry=UC; break;
case 5: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=(((MZ ^ 1))<<0) | (((MC ^ 1))<<1) | (((MN ^ 1))<<2) | (((MV ^ 1))<<3); out_y=u; ct=(UZ ^ 1); carry=UC; break;
case 6: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | (((IV | UV))<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UV; carry=UC; break;
case 7: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | (((IV | UV))<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UV ^ 1); carry=UC; break;
case 8: un=((0)<<0) | ((UC)<<1) | ((UN)<<2) | ((UV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC | UZ); carry=(UC ^ 1); break;
case 9: un=((1)<<0) | ((UC)<<1) | ((UN)<<2) | ((UV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UC ^ 1) & (UZ ^ 1)); carry=(UC ^ 1); break;
case 10: un=((UZ)<<0) | ((0)<<1) | ((UN)<<2) | ((UV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UC; carry=UC; break;
case 11: un=((UZ)<<0) | ((1)<<1) | ((UN)<<2) | ((UV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC ^ 1); carry=UC; break;
case 12: un=((UZ)<<0) | ((UC)<<1) | ((0)<<2) | ((UV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UC ^ 1) | UZ); carry=UC; break;
case 13: un=((UZ)<<0) | ((UC)<<1) | ((1)<<2) | ((UV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC & (UZ ^ 1)); carry=UC; break;
case 14: un=((UZ)<<0) | ((UC)<<1) | ((UN)<<2) | ((0)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(IN ^ MN); carry=UC; break;
case 15: un=((UZ)<<0) | ((UC)<<1) | ((UN)<<2) | ((1)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((IN ^ MN) ^ 1); carry=UC; break;
case 16: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UN ^ UV) | UZ); carry=UC; break;
case 17: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(((UN ^ UV) ^ 1) & (UZ ^ 1)); carry=UC; break;
case 18: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UN ^ UV); carry=UC; break;
case 19: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UN ^ UV) ^ 1); carry=UC; break;
case 20: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UZ; carry=UC; break;
case 21: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UZ ^ 1); carry=UC; break;
case 22: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UV; carry=UC; break;
case 23: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UV ^ 1); carry=UC; break;
case 24: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UC ^ 1) | UZ); carry=(UC ^ 1); break;
case 25: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC & (UZ ^ 1)); carry=(UC ^ 1); break;
case 26: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UC; carry=UC; break;
case 27: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC ^ 1); carry=UC; break;
case 28: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=((UC ^ 1) | UZ); carry=UC; break;
case 29: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UC & (UZ ^ 1)); carry=UC; break;
case 30: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=UN; carry=UC; break;
case 31: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=u; ct=(UN ^ 1); carry=UC; break;
case 32: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=((MN ^ MV) | MZ); carry=MC; break;
case 33: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(((MN ^ MV) ^ 1) & (MZ ^ 1)); carry=MC; break;
case 34: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MN ^ MV); carry=MC; break;
case 35: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=((MN ^ MV) ^ 1); carry=MC; break;
case 36: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=MZ; carry=MC; break;
case 37: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MZ ^ 1); carry=MC; break;
case 38: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=MV; carry=MC; break;
case 39: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MV ^ 1); carry=MC; break;
case 40: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MC | MZ); carry=(MC ^ 1); break;
case 41: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=((MC ^ 1) & (MZ ^ 1)); carry=(MC ^ 1); break;
case 42: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=MC; carry=MC; break;
case 43: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MC ^ 1); carry=MC; break;
case 44: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=((MC ^ 1) | MZ); carry=MC; break;
case 45: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MC & (MZ ^ 1)); carry=MC; break;
case 46: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=MN; carry=MC; break;
case 47: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=m; ct=(MN ^ 1); carry=MC; break;
case 48: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=((IN ^ IV) | IZ); carry=MC; break;
case 49: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(((IN ^ IV) ^ 1) & (IZ ^ 1)); carry=MC; break;
case 50: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IN ^ IV); carry=MC; break;
case 51: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=((IN ^ IV) ^ 1); carry=MC; break;
case 52: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=IZ; carry=MC; break;
case 53: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IZ ^ 1); carry=MC; break;
case 54: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=IV; carry=MC; break;
case 55: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IV ^ 1); carry=MC; break;
case 56: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=((IC ^ 1) | IZ); carry=(MC ^ 1); break;
case 57: un=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | (((IC ^ 1))<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IC & (IZ ^ 1)); carry=(MC ^ 1); break;
case 58: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=IC; carry=MC; break;
case 59: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IC ^ 1); carry=MC; break;
case 60: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=((IC ^ 1) | IZ); carry=MC; break;
case 61: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IC & (IZ ^ 1)); carry=MC; break;
case 62: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=IN; carry=MC; break;
case 63: un=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); mn=((IZ)<<0) | ((IC)<<1) | ((IN)<<2) | ((IV)<<3); out_y=input; ct=(IN ^ 1); carry=MC; break;
}
if(controls&(1u<<13))un=u;
for(unsigned b=0;b<4;++b)if((controls&(1u<<14)) || (controls&(1u<<(15+b))))mn=(mn&~(1u<<b))|(m&(1u<<b));
switch(inst>>11){case 0:carry=0;break;case 1:carry=1;break;case 2:carry=(controls>>12)&1;break;default:break;}
if(!(controls&(1u<<21)))switch((inst>>6)&31){
case 0:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=10;break;
case 1:sh=((0)<<0) | ((1)<<1) | ((0)<<2) | ((1)<<3);en=10;break;
case 2:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((MN)<<3);en=10;mn=(mn&~2u)|(S0<<1);break;
case 3:sh=((0)<<0) | ((1)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 4:sh=((0)<<0) | ((MC)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 5:sh=((0)<<0) | ((MN)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 6:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 7:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((S0)<<3);en=10;mn=(mn&~2u)|(Q0<<1);break;
case 8:sh=((0)<<0) | ((S0)<<1) | ((0)<<2) | ((Q0)<<3);en=10;mn=(mn&~2u)|(S0<<1);break;
case 9:sh=((0)<<0) | ((MC)<<1) | ((0)<<2) | ((Q0)<<3);en=10;mn=(mn&~2u)|(S0<<1);break;
case 10:sh=((0)<<0) | ((S0)<<1) | ((0)<<2) | ((Q0)<<3);en=10;break;
case 11:sh=((0)<<0) | ((IC)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 12:sh=((0)<<0) | ((MC)<<1) | ((0)<<2) | ((S0)<<3);en=10;mn=(mn&~2u)|(Q0<<1);break;
case 13:sh=((0)<<0) | ((Q0)<<1) | ((0)<<2) | ((S0)<<3);en=10;mn=(mn&~2u)|(Q0<<1);break;
case 14:sh=((0)<<0) | (((IN ^ IV))<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 15:sh=((0)<<0) | ((Q0)<<1) | ((0)<<2) | ((S0)<<3);en=10;break;
case 16:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 17:sh=((1)<<0) | ((0)<<1) | ((1)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 18:sh=((0)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=5;break;
case 19:sh=((1)<<0) | ((0)<<1) | ((1)<<2) | ((0)<<3);en=5;break;
case 20:sh=((QN)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 21:sh=((QN)<<0) | ((0)<<1) | ((1)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 22:sh=((QN)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=5;break;
case 23:sh=((QN)<<0) | ((0)<<1) | ((1)<<2) | ((0)<<3);en=5;break;
case 24:sh=((SN)<<0) | ((0)<<1) | ((QN)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 25:sh=((MC)<<0) | ((0)<<1) | ((QN)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 26:sh=((SN)<<0) | ((0)<<1) | ((QN)<<2) | ((0)<<3);en=5;break;
case 27:sh=((MC)<<0) | ((0)<<1) | ((0)<<2) | ((0)<<3);en=5;break;
case 28:sh=((QN)<<0) | ((0)<<1) | ((MC)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 29:sh=((QN)<<0) | ((0)<<1) | ((SN)<<2) | ((0)<<3);en=5;mn=(mn&~2u)|(SN<<1);break;
case 30:sh=((QN)<<0) | ((0)<<1) | ((MC)<<2) | ((0)<<3);en=5;break;
case 31:sh=((QN)<<0) | ((0)<<1) | ((SN)<<2) | ((0)<<3);en=5;break;
}
const unsigned ye=!(controls&(1u<<19)) && (inst&63)!=0,ce=!(controls&(1u<<20));
return {out_y|(ye<<4)|(ct<<5)|(ce<<6)|(carry<<7)|(sh<<8)|(en<<12),un|(mn<<4)};
}
