#!/bin/sh
# Generate thin 4001 ROM wrappers from src/rom/rom_4001_N.hex.
# Each wrapper carries one 141-PF mask as the intel_4001 ROM_INIT
# parameter, plus the chip's board straps (CHIP_NO / IO_DIR).
#
# The wrappers are checked in: regenerate after editing the hex files.
#   sh scripts/gen_rom_wrappers.sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SYSTEM_DIR=$(dirname "$SCRIPT_DIR")
ROM_DIR="$SYSTEM_DIR/src/rom"
OUT_DIR="$SYSTEM_DIR/src"

# CHIP_NO and IO_DIR straps per spec section 3.1:
#   rom0: bits 0-2 drive the 4003 shifters (outputs)
#   rom1: keyboard columns (inputs)   rom2: drum index + paper button
#   rom3/rom4: port unused (inputs, tied low)
CHIP_NO_0=0; IO_DIR_0="4'b0111"
CHIP_NO_1=1; IO_DIR_1="4'b0000"
CHIP_NO_2=2; IO_DIR_2="4'b0000"
CHIP_NO_3=3; IO_DIR_3="4'b0000"
CHIP_NO_4=4; IO_DIR_4="4'b0000"

for n in 0 1 2 3 4; do
    eval "chip_no=\$CHIP_NO_$n"
    eval "io_dir=\$IO_DIR_$n"
    hex=$(perl -e '
        open(my $fh, "<", $ARGV[0]) or die "cannot open $ARGV[0]";
        my @b = map { hex } <$fh>;
        die "expected 256 bytes" unless @b == 256;
        print lc sprintf("%s", join("", map { sprintf("%02x", $_) } reverse @b));
    ' "$ROM_DIR/rom_4001_$n.hex")

    cat > "$OUT_DIR/intel_4001_rom$n.sv" <<EOF
// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_$n.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom$n (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'h$hex;

    intel_4001 #(
        .CHIP_NO   ($chip_no),
        .IO_DIR    ($io_dir),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
EOF
    echo "generated intel_4001_rom$n.sv"
done
