#!/usr/bin/env python3
"""Regenerate the visually corrected example tables in the Markdown manual."""
import json
from pathlib import Path

ref = Path(__file__).resolve().parents[1] / 'spec/reference'
path = ref / 'Unicom_141P_manual.md'
doc = json.loads((ref / 'Unicom_141P_examples.json').read_text(encoding='utf-8'))
marker = '<!-- EXAMPLES: generated by scripts/manual_markdown.py -->'
intro = path.read_text(encoding='utf-8').split(marker)[0].rstrip()
lines = [intro, '', marker, '', '## Operation examples (printed pages 10-32)', '',
         'Each table preserves the key order. Numeric entries are shown as individual keys.',
         'Expected output lists the checked suffix at that step; a dash means no checkpoint,',
         'not necessarily no printing. `*op` means multiplication, `*` means total,',
         '`ST` means diamond/subtotal, `EX` means exchange, and `SQRT` means square root.',
         'The JSON also contains independent setup keys (`CE C CM C`) to isolate replays.',
         'These setup keys are not part of the manual examples.', '']
for e in doc['examples']:
    mode = {0:'FL (floating)',1:'5/4 (round)',8:'IN (truncate)'}[e['switches']['rounding']]
    lines += [f'### {e["id"]}: {e["title"]}', '',
              f'Printed page {e["manual_page"]}; PDF page {e["pdf_page"]}. '
              f'DP={e["switches"]["precision"]}; {mode}.', '']
    if e.get('requires'): lines += ['Square-root model only.', '']
    if e.get('notes'): lines += [e['notes'], '']
    lines += ['| Operation | Expected printed output / lamps |','|---|---|']
    for s in e['steps']:
        operation = ' '.join(s.get('keys',[]))
        if 'switches' in s:
            operation = 'Set '+', '.join(f'{k}={v}' for k,v in s['switches'].items())
        outputs = []
        for r in s.get('expect',{}).get('tape',[]):
            txt = ('dotted overflow line' if r['value'] is None else f'{r["value"]} {r["symbol"]}')
            if r['rounded']: txt += ' (rounded up mark)'
            if r['red']: txt += ' (red)'
            outputs.append(txt)
        outputs += [f'{k} lamp: {"on" if v else "off"}' for k,v in s.get('expect',{}).get('lamps',{}).items()]
        lines.append(f'| `{operation}` | {"; ".join(outputs) or "-"} |')
    lines.append('')
    notes = [s['profile_note'] for s in e['steps'] if 'profile_note' in s]
    if notes:
        lines += ['**Editorial note (recovered ROM):** ' + ' '.join(notes), '']
path.write_text('\n'.join(lines).rstrip()+'\n',encoding='utf-8')
