#!/usr/bin/env python3
"""Generate mathematical CORDIC constants independently of RTL.

Decimal arithmetic, 100 significant digits. No chip internal coefficient
recovery is claimed. Native command/domain bounds come from AMD's brief.
"""
from decimal import Decimal, localcontext, ROUND_HALF_EVEN
from pathlib import Path
import csv, io, argparse

ROOT=Path(__file__).resolve().parents[1]
PI_TEXT='3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679'

def build():
    with localcontext() as ctx:
        ctx.prec=100
        two=Decimal(2); q=two**56; pi=Decimal(PI_TEXT)
        def encoded(x): return int((x*q).to_integral_value(rounding=ROUND_HALF_EVEN))
        def atan(x):
            if x==1:return pi/4
            total=Decimal(0);power=x;square=x*x
            for index in range(200):
                term=power/Decimal(2*index+1)
                total=total+term if index%2==0 else total-term
                power*=square
            return total
        angles=[encoded(atan(two**(-i))) for i in range(52)]
        gain=Decimal(1)
        for i in range(52):gain/=(1+two**(-2*i)).sqrt()
        values={'ONE':int(q),'PI':encoded(pi),'HALF_PI':encoded(pi/2),
                'TWO_PI':encoded(2*pi),'GAIN':encoded(gain),
                'LN2':encoded(two.ln()),'LOG10_E':encoded(1/Decimal(10).ln())}
        wide_pi=int((2*pi*(two**112)).to_integral_value(rounding=ROUND_HALF_EVEN))
    output=['// Generated by generate_derived_constants.py; mathematical Q56 constants.\n']
    for name,value in values.items():output.append(f"localparam logic signed [63:0] Q_{name}=64'sh{value:016x};\n")
    output.append(f"localparam logic [175:0] TWO_PI_Q112=176'h{wide_pi:044x};\n")
    output.append('function automatic logic signed [63:0] cordic_angle(input logic [5:0] index);\n case(index)\n')
    for i,value in enumerate(angles):output.append(f"  6'd{i}: cordic_angle=64'sh{value:016x};\n")
    output.append("  default: cordic_angle=0;\n endcase\nendfunction\n")
    s=io.StringIO(newline='');w=csv.writer(s,lineterminator='\n');w.writerow(['name','fraction_bits','signed_integer'])
    for name,value in values.items():w.writerow([name,56,value])
    w.writerow(['TWO_PI_WIDE',112,wide_pi])
    for i,value in enumerate(angles):w.writerow(['ATAN_2_MINUS_'+str(i),56,value])
    return {ROOT/'src/amd_am9511_derived_constants.svh':''.join(output),ROOT/'references/derived_constants.csv':s.getvalue()}

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,value in build().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=value:raise SystemExit('stale generated file: '+str(path))
        else:path.write_bytes(value.encode('utf-8'))
