module intel_8273_formal;
    (* gclk *) logic clk;
    logic [9:0] cycle=0;
    always_ff @(posedge clk) if (cycle<1000) cycle<=cycle+1'b1;
    logic rst_n,cs_n,rd_n,wr_n,tx_dack_n,rx_dack_n,tx_tick,rx_tick,cts_n,cd_n,rxd;
    logic [1:0] addr;
    logic [7:0] data_i,data_o;
    logic data_oe,tx_drq,rx_drq,tx_int,rx_int,txd,dpll_tick,rts_n,flag_det_n;
    logic [3:0] port_b;
`ifdef FORMAL_COVER
    assign rst_n=cycle!=0;
    always_comb begin
        cs_n=1; rd_n=1; wr_n=1; tx_dack_n=1; rx_dack_n=1;
        tx_tick=0; rx_tick=0; cts_n=0; cd_n=0; rxd=1; addr=0; data_i=0;
        case(cycle)
            2: begin cs_n=0; wr_n=0; data_i=8'h91; end
            4: begin cs_n=0; wr_n=0; addr=1; data_i=8'h24; end
`ifdef COVER_TX
            6: begin cs_n=0; wr_n=0; data_i=8'hc8; end
            8: begin cs_n=0; wr_n=0; addr=1; data_i=0; end
            10: begin cs_n=0; wr_n=0; addr=1; data_i=0; end
            12: begin cs_n=0; wr_n=0; addr=1; data_i=8'h42; end
            14: begin cs_n=0; wr_n=0; addr=1; data_i=8'h13; end
`else
            6: begin cs_n=0; wr_n=0; data_i=8'hc0; end
            8: begin cs_n=0; wr_n=0; addr=1; data_i=8'h10; end
            10: begin cs_n=0; wr_n=0; addr=1; data_i=0; end
`endif
            default: begin end
        endcase
`ifdef COVER_TX
        if (cycle>=18) tx_tick=1;
`elsif COVER_RX
        // Independent supervisory frame 42 13 FCS 8B 58, LSB-first.
        // See references/README.md; exact CRC bytes generated by binascii oracle.
        if (cycle>=16 && cycle<64) begin
            rx_tick=1; rxd=(48'h7e588b13427e >> (cycle-16)) & 1;
        end
`else
        if (cycle==16) cd_n=1;
`endif
    end
`else
    (* anyseq *) logic [24:0] stimulus;
    assign {cs_n,rd_n,wr_n,tx_dack_n,rx_dack_n,tx_tick,rx_tick,cts_n,cd_n,rxd,addr,data_i}=stimulus[19:0];
    assign rst_n=cycle!=0;
`endif
    intel_8273 dut (
        .clk(clk),.rst_n(rst_n),.cs_n(cs_n),.rd_n(rd_n),.wr_n(wr_n),.addr(addr),
        .data_i(data_i),.data_o(data_o),.data_oe(data_oe),.tx_dack_n(tx_dack_n),
        .rx_dack_n(rx_dack_n),.tx_drq(tx_drq),.rx_drq(rx_drq),.tx_int(tx_int),.rx_int(rx_int),
        .tx_tick(tx_tick),.rx_tick(rx_tick),.tx_sample_tick(rx_tick),.clk32_tick(rx_tick),
        .rxd(rxd),.txd(txd),.dpll_tick(dpll_tick),.cts_n(cts_n),.cd_n(cd_n),
        .port_a(3'd0),.port_b(port_b),.rts_n(rts_n),.flag_det_n(flag_det_n)
    );
endmodule
