// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_2.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom2 (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'hc0b3ed29b2ed27c0f179e0fbeb29d06ef11a8ddbc0e4f4ec29c0bddfe42766f7d652c1f682ec29b2ec27b685d4c0baf7bb828ba3f952c0f1ba99baf3bb93baf7ba82f19bddf952c242e5eff952c242bbb3d1c1fab5d3c0495146510a51c6414a51f0e6d8a11cee274026bda46540f5f5d1fa8f1cf19c5c425614f79ba78a52da831cf1978314aa8a523f42b250e129d26e198a52ae8a52af8f52681caa7777e9276142dfba5f1cf19fddb86a50c04b7bb050e14b11d8002e0c2a537de2e1f03f113714f7a251b9ab6b68b050e1f7f6ecbdd22c11bbedbaed29bea42642f6def3f6bebfa42514f78fd12642a5bfdf177f2c42e029b9dfbaff2e4a51da107fbff4;

    intel_4001 #(
        .CHIP_NO   (2),
        .IO_DIR    (4'b0000),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
