// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_3.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom3 (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'hf1fa09f144fa09f10d040c030e02fdf3dab7c25fddedceca00eea7e874f3e75fbcf35fe39a53dfa9d7f1fdeffc460bd375d56cf17f4afc4ad94982ef8aacb7ffb4bf0d01bc2c1ebd313c31bd971eb7d4e7b0bc03c6fcabdb3ca79e9ae9f1a8b4ebfda377aab17bae8298a79775986c98a7d96675666c3ca77c9a53dd7ca75fca84ce9acfdf9e6e7bb410b1c20d6aa70c041ca7024776906f7bfe67a7cacafef38656a7dd5a5e3ccf40a051a7214dac56a95a5e52490ee5e3038d40a75ddd73ce5df185ff24a7dd3ccf5322a7ca5229a7523fa9512129345151e5369a329ee173a0483ca28d46760f7b0f6dfcef8702048dfb0fa7fcd90e75146ced4b4030c032;

    intel_4001 #(
        .CHIP_NO   (3),
        .IO_DIR    (4'b0000),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
