// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_0.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom0 (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'hc0fd1910260028e7dfe4a969e0a27a1ce92969e0a329b9ecf71cf7f2eff814f7f5a229bf776450b282d0b383b2f6faf5b261147a40cd79a9771cf7f5a2b9fcea276550d100221826b479645007286a50c5cad7d7f961058afdd7cdf1989106bf0ea4ad0d1d4d7d062d5d8dbd3d6d9d0c0512221831410558681a195363c7bbf7404a51f00028d914a9c0bcf0761a6d73f6ea2320226cc0e2d0e229d3d440d402435714f74b14605a710051005310282026b0504f110000f0001a85fcf5f3d1e1d073516830b1a5a02034e6ea276450e7ea27e4f8f8ecb0004046520014f7f5ea2766e1f5b3f3a051f068b3f5ec27735168291cad5f51f0b1ad5f51b0500111f0;

    intel_4001 #(
        .CHIP_NO   (0),
        .IO_DIR    (4'b0111),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
