// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_4.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom4 (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044102414b4000264020e627005f41c1bff8afc1fa6a967bc0f08779e0d98e1297e929f3b9afc07d79e0fbeb29d0fab9afc1f3f6b7baf7bb8ef6abf6bab7ab6d2ec0bbed29bd9a41a241214134410441534168684a414841fe41330000000000000000002e935936967a9f5ba9359857855f415d7a58366a555b9c4463653e6153a7510000000000000000000000000000000244300e14f702146011715054f03210282026b05006112820;

    intel_4001 #(
        .CHIP_NO   (4),
        .IO_DIR    (4'b0000),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
