// GENERATED by scripts/gen_rom_wrappers.sh from src/rom/rom_4001_1.hex.
// Do not edit by hand: change the hex file and regenerate.
module intel_4001_rom1 (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       clr_n,
    input  logic [3:0] data_i,
    output logic [3:0] data_o,
    output logic       data_oe,
    input  logic       sync,
    input  logic       cm_rom,
    input  logic [3:0] port_i,
    output logic [3:0] port_o,
    output logic [3:0] port_oe
);
    localparam logic [2047:0] MASK = 2048'hbf6f6f6f6f6f6f0040002a81518151805100444642ec42e742de42ca42b942b342ae42aa42a342944200d342c19ad0f39bddc06acd7bc0bbed29c0e5ab29b885d4c1f6a4c1f3b5f6a5c184dcc195d7c1f3bdf8adc1fbadc1f3a279ebdf2968bdb9dea241b9deb885d4c0e6f6faf5ee278241a48141d88141d16666c0e627666666c1f5ee27c1f6ee2968686868c1f3f8ee296868c0611ca9e0bde929b9f1f8a9bd6868adb9dec05379e0bde9296868c0e5e44a79e029686868686868c16d431a357769e0fbeb27f1e829f9fab685d43341b885d4c0f1217769e0fbeb27e929b685d4c0e4b3e529edb3ec270e7769e029e92766666666660e41b6b886f2f2a533;

    intel_4001 #(
        .CHIP_NO   (1),
        .IO_DIR    (4'b0000),
        .ROM_INIT  (MASK)
    ) u_4001 (
        .*
    );
endmodule
